Repository stjude-rust-labs/wdl, pull requests merged in 2025-03, with the labels that each got.

#362 fix: lsp errors out when a file uri is received instead of directory
  wdl-lsp/CHANGELOG.md
  wdl-lsp/src/server.rs
Labels: S-awaiting-revisions

#343 feat: implement `DisallowedDeclarationName` rule
  Arena.toml
  wdl-lint/CHANGELOG.md
  wdl-lint/RULES.md
  wdl-lint/src/lib.rs
  wdl-lint/src/rules.rs
  wdl-lint/src/rules/disallowed_declaration_name.rs
  wdl-lint/src/rules/snake_case.rs
  wdl-lint/tests/lints/deprecated-object/source.wdl
  wdl-lint/tests/lints/disallowed-declaration-name/source.errors
  wdl-lint/tests/lints/disallowed-declaration-name/source.wdl
  wdl-lint/tests/lints/disallowed-input-name/source.errors
  wdl-lint/tests/lints/disallowed-input-name/source.wdl
Labels: S-awaiting-pass-CI, S-awaiting-revisions

#352 feat: add YAML input format support to wdl-engine
  wdl-engine/CHANGELOG.md
  wdl-engine/Cargo.toml
  wdl-engine/src/inputs.rs
  wdl-engine/tests/inputs.rs
  wdl-engine/tests/inputs/call-input-present/inputs.yaml
  wdl-engine/tests/inputs/complex-types/inputs.yaml
  wdl-engine/tests/inputs/default-workflow-inputs/inputs.yaml
  wdl-engine/tests/inputs/empty/inputs.yaml
  wdl-engine/tests/inputs/explicit-nested-inputs-not-allowed/inputs.yaml
  wdl-engine/tests/inputs/invalid-hints-type/inputs.yaml
  wdl-engine/tests/inputs/invalid-requirement-type/inputs.yaml
  wdl-engine/tests/inputs/invalid-runtime-type/inputs.yaml
  wdl-engine/tests/inputs/invalid-wdl-array/inputs.yaml
  wdl-engine/tests/inputs/known-requirement/inputs.yaml
  wdl-engine/tests/inputs/missing-call-input/inputs.yaml
  wdl-engine/tests/inputs/missing-file/inputs.yaml
  wdl-engine/tests/inputs/missing-prefix/inputs.yaml
  wdl-engine/tests/inputs/missing-task-input/inputs.yaml
  wdl-engine/tests/inputs/missing-workflow-input/inputs.yaml
  wdl-engine/tests/inputs/nested-input-already-specified/inputs.yaml
  wdl-engine/tests/inputs/nested-inputs-not-allowed/inputs.yaml
  wdl-engine/tests/inputs/unknown-call-1_2/inputs.yaml
  wdl-engine/tests/inputs/unknown-call/inputs.yaml
  wdl-engine/tests/inputs/unknown-hint/inputs.yaml
  wdl-engine/tests/inputs/unknown-nested-input/inputs.yaml
  wdl-engine/tests/inputs/unknown-requirement/inputs.yaml
  wdl-engine/tests/inputs/unknown-task-input/inputs.yaml
  wdl-engine/tests/inputs/unknown-task-or-workflow/inputs.yaml
  wdl-engine/tests/inputs/unknown-workflow-input/inputs.yaml
Labels: S-awaiting-review

#371 feat: Enable linking between related lint rules
  CONTRIBUTING.md
  wdl-lint/CHANGELOG.md
  wdl-lint/RULES.md
  wdl-lint/src/lib.rs
  wdl-lint/src/rules/blank_lines_between_elements.rs
  wdl-lint/src/rules/call_input_spacing.rs
  wdl-lint/src/rules/command_mixed_indentation.rs
  wdl-lint/src/rules/comment_whitespace.rs
  wdl-lint/src/rules/container_value.rs
  wdl-lint/src/rules/deprecated_object.rs
  wdl-lint/src/rules/deprecated_placeholder_option.rs
  wdl-lint/src/rules/description_missing.rs
  wdl-lint/src/rules/disallowed_declaration_name.rs
  wdl-lint/src/rules/disallowed_input_name.rs
  wdl-lint/src/rules/disallowed_output_name.rs
  wdl-lint/src/rules/double_quotes.rs
  wdl-lint/src/rules/ending_newline.rs
  wdl-lint/src/rules/expression_spacing.rs
  wdl-lint/src/rules/import_placement.rs
  wdl-lint/src/rules/import_sort.rs
  wdl-lint/src/rules/import_whitespace.rs
  wdl-lint/src/rules/inconsistent_newlines.rs
  wdl-lint/src/rules/input_not_sorted.rs
  wdl-lint/src/rules/key_value_pairs.rs
  wdl-lint/src/rules/line_width.rs
  wdl-lint/src/rules/malformed_lint_directive.rs
  wdl-lint/src/rules/matching_parameter_meta.rs
  wdl-lint/src/rules/misplaced_lint_directive.rs
  wdl-lint/src/rules/missing_metas.rs
  wdl-lint/src/rules/missing_output.rs
  wdl-lint/src/rules/missing_requirements.rs
  wdl-lint/src/rules/missing_runtime.rs
  wdl-lint/src/rules/no_curly_commands.rs
  wdl-lint/src/rules/nonmatching_output.rs
  wdl-lint/src/rules/pascal_case.rs
  wdl-lint/src/rules/preamble_comment_after_version.rs
  wdl-lint/src/rules/preamble_formatting.rs
  wdl-lint/src/rules/redundant_input_assignment.rs
  wdl-lint/src/rules/runtime_section_keys.rs
  wdl-lint/src/rules/section_order.rs
  wdl-lint/src/rules/shellcheck.rs
  wdl-lint/src/rules/snake_case.rs
  wdl-lint/src/rules/todo.rs
  wdl-lint/src/rules/trailing_comma.rs
  wdl-lint/src/rules/unknown_rule.rs
  wdl-lint/src/rules/version_formatting.rs
  wdl-lint/src/rules/whitespace.rs
  wdl-lint/tests/lints/section-ordering/source.errors
Labels: S-needs-review
